# Generated by Django 4.2.5 on 2023-10-03 05:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("is_alum", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(blank=True, upload_to="images/profile_pics/"),
                ),
                ("fullname", models.CharField(default="", max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("is_alumni", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("address", models.CharField(default="", max_length=500)),
                ("personal_email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                (
                    "hostel",
                    models.CharField(
                        choices=[
                            ("hostel_1", "Hostel 1"),
                            ("hostel_2", "Hostel 2"),
                            ("hostel_3", "Hostel 3"),
                            ("hostel_4", "Hostel 4"),
                            ("hostel_5", "Hostel 5"),
                            ("hostel_6", "Hostel 6"),
                            ("hostel_7", "Hostel 7"),
                            ("hostel_8", "Hostel 8"),
                            ("hostel_9", "Hostel 9"),
                            ("hostel_10", "Hostel 10"),
                            ("hostel_11", "Hostel 11"),
                            ("hostel_12", "Hostel 12"),
                            ("hostel_13", "Hostel 13"),
                            ("hostel_14", "Hostel 14"),
                            ("hostel_15", "Hostel 15"),
                            ("hostel_16", "Hostel 16"),
                            ("hostel_17", "Hostel 17"),
                            ("hostel_18", "Hostel 18"),
                        ],
                        max_length=255,
                    ),
                ),
                ("room_no", models.CharField(max_length=10)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Aerospace Engineering", "Aerospace Engineering"),
                            ("Animation", "Animation"),
                            (
                                "Application Software Centre",
                                "Application Software Centre",
                            ),
                            ("Applied Geophysics", "Applied Geophysics"),
                            (
                                "Applied Statistics and Informatics",
                                "Applied Statistics and Informatics",
                            ),
                            ("Biomedical Engineering", "Biomedical Engineering"),
                            (
                                "Biosciences and Bioengineering",
                                "Biosciences and Bioengineering",
                            ),
                            ("Biotechnology", "Biotechnology"),
                            (
                                "Centre for Aerospace Systems Design and Engineering",
                                "Centre for Aerospace Systems Design and Engineering",
                            ),
                            (
                                "Centre for Distance Engineering Education Programme",
                                "Centre for Distance Engineering Education Programme",
                            ),
                            (
                                "Environmental Science and Engineering",
                                "Environmental Science and Engineering",
                            ),
                            (
                                "Centre for Formal Design and Verification of Software",
                                "Centre for Formal Design and Verification of Software",
                            ),
                            (
                                "Centre for Research in Nanotechnology and Science",
                                "Centre for Research in Nanotechnology and Science",
                            ),
                            (
                                "Centre for Technology Alternatives for Rural Areas",
                                "Centre for Technology Alternatives for Rural Areas",
                            ),
                            (
                                "Centre for Urban Science and Engineering",
                                "Centre for Urban Science and Engineering",
                            ),
                            (
                                "Centre of Studies in Resources Engineering",
                                "Centre of Studies in Resources Engineering",
                            ),
                            ("Chemical Engineering", "Chemical Engineering"),
                            ("Chemistry", "Chemistry"),
                            ("Civil Engineering", "Civil Engineering"),
                            ("Climate Studies", "Climate Studies"),
                            ("Computer Centre", "Computer Centre"),
                            (
                                "Computer Science & Engineering",
                                "Computer Science & Engineering",
                            ),
                            (
                                "Continuing Education Programme",
                                "Continuing Education Programme",
                            ),
                            (
                                "Corrosion Science and Engineering",
                                "Corrosion Science and Engineering",
                            ),
                            (
                                "Desai Sethi Centre for Entrepreneurship",
                                "Desai Sethi Centre for Entrepreneurship",
                            ),
                            ("Earth Sciences", "Earth Sciences"),
                            ("Educational Technology", "Educational Technology"),
                            ("Electrical Engineering", "Electrical Engineering"),
                            (
                                "Energy Science and Engineering",
                                "Energy Science and Engineering",
                            ),
                            ("Economics (HSS)", "Economics (HSS)"),
                            ("Engineering Physics", "Engineering Physics"),
                            (
                                "Humanities & Social Science",
                                "Humanities & Social Science",
                            ),
                            (
                                "IITB-Monash Research Academy",
                                "IITB-Monash Research Academy",
                            ),
                            ("Industrial Design Centre", "Industrial Design Centre"),
                            (
                                "Industrial Engineering and Operations Research",
                                "Industrial Engineering and Operations Research",
                            ),
                            ("Industrial Management", "Industrial Management"),
                            ("Interaction Design", "Interaction Design"),
                            (
                                "Kanwal Rekhi School of Information Technology",
                                "Kanwal Rekhi School of Information Technology",
                            ),
                            ("Material Science", "Material Science"),
                            (
                                "Materials, Manufacturing and Modelling",
                                "Materials, Manufacturing and Modelling",
                            ),
                            ("Mathematics", "Mathematics"),
                            ("Mechanical Engineering", "Mechanical Engineering"),
                            (
                                "Metallurgical Engineering & Materials Science",
                                "Metallurgical Engineering & Materials Science",
                            ),
                            (
                                "Mobility and Vehicle Design",
                                "Mobility and Vehicle Design",
                            ),
                            (
                                "National Centre for Aerospace Innovation and Research",
                                "National Centre for Aerospace Innovation and Research",
                            ),
                            (
                                "National Centre for Mathematics",
                                "National Centre for Mathematics",
                            ),
                            ("Physical Education", "Physical Education"),
                            ("Physics", "Physics"),
                            ("Physics, Material Science", "Physics, Material Science"),
                            ("Preparatory Course", "Preparatory Course"),
                            ("Reliability Engineering", "Reliability Engineering"),
                            (
                                "Shailesh J. Mehta School of Management",
                                "Shailesh J. Mehta School of Management",
                            ),
                            (
                                "Sophisticated Analytical Instrument Facility",
                                "Sophisticated Analytical Instrument Facility",
                            ),
                            (
                                "Systems and Control Engineering",
                                "Systems and Control Engineering",
                            ),
                            (
                                "Tata Center for Technology and Design",
                                "Tata Center for Technology and Design",
                            ),
                            (
                                "Technology and Development",
                                "Technology and Development",
                            ),
                            ("Visual Communication", "Visual Communication"),
                            (
                                "Wadhwani Research Centre for Bioengineering",
                                "Wadhwani Research Centre for Bioengineering",
                            ),
                            ("Centre for Policy Studies", "Centre for Policy Studies"),
                            ("Institute Body", "Institute Body"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        choices=[
                            ("ug", "Undergraduate"),
                            ("dd", "Dual Degree"),
                            ("pg", "Postgraduate"),
                            ("idddp", "Inter-Disciplinary Dual Degree"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("FYBS", "Four Year BS"),
                            ("BTECH", "Bachelor of Technology"),
                            ("MTECH", "Master of Technology"),
                            ("DD", "B.Tech. + M.Tech. Dual Degree"),
                            ("MSC", "Master of Science"),
                            ("PHD", "Doctor of Philosophy"),
                            ("BDES", "Bachelor of Design"),
                            ("MDES", "Master of Design"),
                            ("MPHIL", "Master of Philosophy"),
                            ("MMG", "Master of Management"),
                            ("MSEx", "M.S. (Exit Degree)"),
                            ("MtechEx", "Master of Technology (Exit Degree)"),
                            ("MtechPhDDD", "M.Tech. + Ph.D. Dual Degree"),
                            ("PC", "Preparatory Course"),
                            ("VS", "Visiting Student"),
                            ("MPhilEx", "Master of Philosophy (Exit Degree)"),
                            ("MScEx", "Master of Science (Exit Degree)"),
                            ("MScMTechDD", "M.Sc. + M.Tech. Dual Degree"),
                            ("MScPhDDD", "M.Sc. + Ph.D. Dual Degree"),
                            ("MPhilPhDDD", "M.Phil. + Ph.D. Dual Degree"),
                            ("EMBA", "Executive MBA"),
                            ("IMTECH", "Integrated M.Tech."),
                            ("MSCBR", "Master of Science By Research"),
                            ("TYMSC", "Two Year M.Sc."),
                            ("FYIMSC", "Five Year Integrated M.Sc."),
                            ("DIIT", "D.I.I.T."),
                            ("DIITEx", "D.I.T.T. (Exit Degree)"),
                            ("_", "_"),
                        ],
                        max_length=50,
                    ),
                ),
                ("join_year", models.IntegerField()),
                ("graduation_year", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("P", "Prefer not to say"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "career",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Higher studies", "Higher Studies"),
                            ("Software", "Software Engineering"),
                            ("AI/ML", "AI/ML"),
                            ("Core", "Core Engineering"),
                            ("Entrepreneurship", "Entrepreneurship"),
                            ("Analytics", "Analytics"),
                            ("Finance", "Finance"),
                            ("Consulting", "Consulting"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
