version: '2.2'

services:
  aluminationbackend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8012:8000"
    entrypoint: /backend/wsgi-entrypoint.sh
    volumes:
      - ./backend:/backend/
    expose:
      - 8000
    networks:
      - mynetwork
  

  aluminationfrontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    volumes:
      - ./frontend:/frontend
    networks:
      - mynetwork

networks:
  mynetwork:
    name: yearbook23_mynetwork