DEGREES = [
    ("FYBS", "Four Year BS"),
    ("BTECH", "Bachelor of Technology"),
    ("MTECH", "Master of Technology"),
    ("DD", "B.Tech. + M.Tech. Dual Degree"),
    ("MSC", "Master of Science"),
    ("PHD", "Doctor of Philosophy"),
    ("BDES", "Bachelor of Design"),
    ("MDES", "Master of Design"),
    ("MPHIL", "Master of Philosophy"),
    ("MMG", "Master of Management"),
    ("MSEx", "M.S. (Exit Degree)"),
    ("MtechEx", "Master of Technology (Exit Degree)"),
    ("MtechPhDDD", "M.Tech. + Ph.D. Dual Degree"),
    ("PC", "Preparatory Course"),
    ("VS", "Visiting Student"),
    ("MPhilEx", "Master of Philosophy (Exit Degree)"),
    ("MScEx", "Master of Science (Exit Degree)"),
    ("MScMTechDD", "M.Sc. + M.Tech. Dual Degree"),
    ("MScPhDDD", "M.Sc. + Ph.D. Dual Degree"),
    ("MPhilPhDDD", "M.Phil. + Ph.D. Dual Degree"),
    ("EMBA", "Executive MBA"),
    ("IMTECH", "Integrated M.Tech."),
    ("MSCBR", "Master of Science By Research"),
    ("TYMSC", "Two Year M.Sc."),
    ("FYIMSC", "Five Year Integrated M.Sc."),
    ("DIIT", "D.I.I.T."),
    ("DIITEx", "D.I.T.T. (Exit Degree)"),
    ("_","_"),
]


DEGREES_MOD = [
    ("BS", "Four Year BS"),
    ("BTech", "Bachelor of Technology"),
    ("MTech", "Master of Technology"),
    ("DD", "B.Tech. + M.Tech. Dual Degree"),
    ("MSc", "Master of Science"),
    ("PhD", "Doctor of Philosophy"),
    ("BDes", "Bachelor of Design"),
    ("MDes", "Master of Design"),
    ("M.Phil", "Master of Philosophy"),
    ("MMG", "Master of Management"),
    ("MSEx", "M.S. (Exit Degree)"),
    ("MTechEx", "Master of Technology (Exit Degree)"),
    ("MTechPhDDD", "M.Tech. + Ph.D. Dual Degree"),
    ("PC", "Preparatory Course"),
    ("VS", "Visiting Student"),
    ("MPhilEx", "Master of Philosophy (Exit Degree)"),
    ("MScEx", "Master of Science (Exit Degree)"),
    ("MScMTechDD", "M.Sc. + M.Tech. Dual Degree"),
    ("MScPhDDD", "M.Sc. + Ph.D. Dual Degree"),
    ("MPhilPhDDD", "M.Phil. + Ph.D. Dual Degree"),
    ("EMBA", "Executive MBA"),
    ("IMTech", "Integrated M.Tech."),
    ("MScBR", "Master of Science By Research"),
    ("TYMSc", "Two Year M.Sc."),
    ("FYIMSc", "Five Year Integrated M.Sc."),
    ("DIIT", "D.I.I.T."),
    ("DIITEx", "D.I.T.T. (Exit Degree)"),
]


HOSTEL_CHOICES = (
    ("hostel_1", "Hostel 1"),
    ("hostel_2", "Hostel 2"),
    ("hostel_3", "Hostel 3"),
    ("hostel_4", "Hostel 4"),
    ("hostel_5", "Hostel 5"),
    ("hostel_6", "Hostel 6"),
    ("hostel_7", "Hostel 7"),
    ("hostel_8", "Hostel 8"),
    ("hostel_9", "Hostel 9"),
    ("hostel_10", "Hostel 10"),
    ("hostel_11", "Hostel 11"),
    ("hostel_12", "Hostel 12"),
    ("hostel_13", "Hostel 13"),
    ("hostel_14", "Hostel 14"),
    ("hostel_15", "Hostel 15"),
    ("hostel_16", "Hostel 16"),
    ("hostel_17", "Hostel 17"),
    ("hostel_18", "Hostel 18"),
)

DEPARTMENTS = {
    "Aerospace Engineering": "Aerospace Engg",
    "Animation": "Animation",
    "Application Software Centre": "ASC",
    "Applied Geophysics": "Applied Geophysics",
    "Applied Statistics and Informatics": "ASI",
    "Biomedical Engineering": "Biomedical Engg",
    "Biosciences and Bioengineering": "Biosciences & BioEngg",
    "Biotechnology": "Biotechnology",
    "Centre for Aerospace Systems Design and Engineering": "CASDE",
    "Centre for Distance Engineering Education Programme": "CDEEP",
    "Environmental Science and Engineering": "ESE",
    "Centre for Formal Design and Verification of Software": "CFDVS",
    "Centre for Research in Nanotechnology and Science": "CRNS",
    "Centre for Technology Alternatives for Rural Areas": "CTARA",
    "Center for Machine Intelligence and Data Science": "CMIDS",
    "Centre for Urban Science and Engineering": "CUSE",
    "Centre of Studies in Resources Engineering": "CSRE",
    "Chemical Engineering": "Chemical Engg",
    "Chemistry": "Chemistry",
    "Civil Engineering": "Civil Engg",
    "Climate Studies": "Climate Studies",
    "Computer Centre": "CC",
    "Computer Science & Engineering": "CSE",
    "Continuing Education Programme": "CEP",
    "Corrosion Science and Engineering": "Corrosion Science & Engg",
    "Desai Sethi Centre for Entrepreneurship": "DSCE",
    "Earth Sciences": "Earth Sciences",
    "Educational Technology": "Educational Technology",
    "Electrical Engineering": "EE",
    "Energy Science and Engineering": "Energy Science and Engg",
    "Economics (HSS)": "Economics",
    "Engineering Physics": "Engineering Physics",
    "Humanities & Social Science": "HSS",
    "IITB-Monash Research Academy": "IITB-Monash",
    "Industrial Design Centre": "IDC",
    "Industrial Engineering and Operations Research": "IEOR",
    "Industrial Management": "Industrial Management",
    "Interaction Design": "Interaction Design",
    "Kanwal Rekhi School of Information Technology": "KRSIT",
    "Material Science": "Material Science",
    "Materials, Manufacturing and Modelling": "Materials, Manufacturing and Modelling",
    "Mathematics": "Mathematics",
    "Mechanical Engineering": "Mechanical Engg",
    "Metallurgical Engineering & Materials Science": "MEMS",
    "Mobility and Vehicle Design": "Mobility and Vehicle Design",
    "National Centre for Aerospace Innovation and Research": "NCAIR",
    "National Centre for Mathematics": "NCM",
    "Physical Education": "Physical Education",
    "Physics": "Physics",
    "Physics, Material Science": "Physics, Material Science",
    "Preparatory Course": "Preparatory Course",
    "Reliability Engineering": "Reliability Engineering",
    "Shailesh J. Mehta School of Management": "SJM-SOM",
    "Sophisticated Analytical Instrument Facility": "Sophisticated Analytical Instrument Facility",
    "Systems and Control Engineering": "SysCon Engg",
    "Tata Center for Technology and Design": "Tata Center",
    "Technology and Development": "Tech and Dev",
    "Visual Communication": "Visual Communication",
    "Wadhwani Research Centre for Bioengineering": "Wadhwani Research Centre",
    "Centre for Policy Studies": "Centre for Policy Studies",
    "Institute Body": "Institute Body",
}





GENDER = [("M", "Male"), ("F", "Female"), ("O", "Other"), ("P", "Prefer not to say")]

CAREER = [
    ("Student", "Student"),
    ("Higher studies", "Higher Studies"),
    ("Software", "Software Engineering"),
    ("AI/ML", "AI/ML"),
    ("Core", "Core Engineering"),
    ("Entrepreneurship", "Entrepreneurship"),
    ("Analytics", "Analytics"),
    ("Finance", "Finance"),
    ("Consulting", "Consulting"),
    ("Other", "Other"),
]
